name: MOC
favicon: null
layout_spectrum: 0.78061
typography_spectrum: 0.39021
title: Computer forms since 1980
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#df0001'
    - '#392a31'
    - '#959094'
    - '#f2727e'
  brandStrength: 0.5625
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
